# Generated by Django 5.2 on 2025-04-21 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AxeCoreViolacoes',
            fields=[
                ('violacao', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('impact', models.CharField(default='impact', max_length=255)),
                ('description', models.CharField(default='description', max_length=255)),
                ('help', models.CharField(default='help', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SiteAnalisado',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeficiencia',
            fields=[
                ('deficiencia', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAnaliseSite',
            fields=[
                ('pk', models.CompositePrimaryKey('url', 'violacao', blank=True, editable=False, primary_key=True, serialize=False)),
                ('nodes', models.CharField(default='nodes', max_length=255)),
                ('violacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultado_analise_site.axecoreviolacoes')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultado_analise_site.siteanalisado')),
            ],
        ),
        migrations.CreateModel(
            name='ViolacaoTipoDeficiencia',
            fields=[
                ('pk', models.CompositePrimaryKey('violacao', 'deficiencia', blank=True, editable=False, primary_key=True, serialize=False)),
                ('deficiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultado_analise_site.tipodeficiencia')),
                ('violacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultado_analise_site.axecoreviolacoes')),
            ],
        ),
    ]
