# Generated by Django 5.2 on 2025-04-21 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado_analise_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violacaotipodeficiencia',
            name='pk',
        ),
        migrations.AlterField(
            model_name='violacaotipodeficiencia',
            name='violacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='resultado_analise_site.axecoreviolacoes', unique=True),
        ),
    ]
