# Generated by Django 5.2 on 2025-04-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado_analise_site', '0002_remove_violacaotipodeficiencia_pk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCategoria',
            fields=[
                ('categoria', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='siteanalisado',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resultado_analise_site.sitecategoria'),
        ),
    ]
