# Generated by Django 5.2 on 2025-04-21 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado_analise_site', '0003_sitecategoria_siteanalisado_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='axecoreviolacoes',
            name='deficiencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resultado_analise_site.tipodeficiencia'),
        ),
    ]
