# Generated by Django 5.2 on 2025-04-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado_analise_site', '0004_axecoreviolacoes_deficiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoanalisesite',
            name='incomplete',
            field=models.BooleanField(default=False),
        ),
    ]
