# Generated by Django 5.2 on 2025-04-28 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado_analise_site', '0005_resultadoanalisesite_incomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='violacaotipodeficiencia',
            name='pk',
            field=models.CompositePrimaryKey('violacao', 'deficiencia', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='violacaotipodeficiencia',
            name='violacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultado_analise_site.axecoreviolacoes'),
        ),
    ]
