# Generated by Django 5.2 on 2025-04-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado_analise_site', '0006_violacaotipodeficiencia_pk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violacaotipodeficiencia',
            name='exist',
            field=models.BooleanField(default=False),
        ),
    ]
