# Generated by Django 5.2 on 2025-04-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado_analise_site', '0007_violacaotipodeficiencia_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='axecoreviolacoes',
            name='revisao_manual',
            field=models.BooleanField(default=False),
        ),
    ]
