# Generated by Django 5.2 on 2025-04-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultado_analise_site', '0008_axecoreviolacoes_revisao_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='axecoreviolacoes',
            name='revisao_manual',
        ),
    ]
