# Generated by Django 5.2 on 2025-04-28 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultado_analise_site', '0009_remove_axecoreviolacoes_revisao_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='axecoreviolacoes',
            name='deficiencia',
        ),
    ]
