# Generated by Django 5.2 on 2025-04-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado_analise_site', '0010_remove_axecoreviolacoes_deficiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='axecoreviolacoes',
            name='index',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='sitecategoria',
            name='index',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='tipodeficiencia',
            name='index',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
