# Generated by Django 5.2 on 2025-05-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultado_analise_site', '0011_axecoreviolacoes_index_sitecategoria_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='axecoreviolacoes',
            name='help',
        ),
    ]
