# Generated by Django 5.2 on 2025-05-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultado_analise_site', '0012_remove_axecoreviolacoes_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoanalisesite',
            name='nodes',
        ),
    ]
