# Generated by Django 5.2 on 2025-05-21 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado_analise_site', '0013_remove_resultadoanalisesite_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioWCAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=255, unique=True)),
                ('prioridade', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ViolacaoCriterioWCAG',
            fields=[
                ('pk', models.CompositePrimaryKey('criterio', 'violacao', blank=True, editable=False, primary_key=True, serialize=False)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultado_analise_site.criteriowcag')),
                ('violacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultado_analise_site.axecoreviolacoes')),
            ],
        ),
    ]
