# Generated by Django 5.2 on 2025-05-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado_analise_site', '0014_criteriowcag_violacaocriteriowcag'),
    ]

    operations = [
        migrations.AddField(
            model_name='violacaocriteriowcag',
            name='exist',
            field=models.BooleanField(default=False),
        ),
    ]
