from django.urls import path, re_path
from . import views


urlpatterns = [
    re_path(r'^$',
            views.get_pagina_inicial,
            name='get_pagina_inicial'
    ),
    re_path(
        r'^api/v1/resultado_analise_site/(?P<url>.+)/(?P<violacao>.+)$',
        views.get_delete_update_resultado_analise_site,
        name='get_delete_update_resultado_analise_site'
    ),
    re_path(
        r'^api/v1/resultado_analise_site/$',
        views.get_post_resultado_analise_site,
        name='get_post_resultado_analise_site'
    ),
    re_path(
        r'^todos_resultados_analise_site/$',
        views.get_todos_resultados_analise_site,
        name='get_todos_resultados_analise_site'
    ),
    re_path(
        r'^analisa_site/$',
        views.get_url_analise_site,
        name='get_url_analise_site'
    ),
    re_path(
        r'^analise_resultados/$',
        views.get_analise_resultados,
        name='get_analise_resultados'
    ),
    re_path(
        r'^classifica_violacao/$',
        views.get_classifica_violacao,
        name='get_classifica_violacao'
    ),
    re_path(
        r'^categoriza_site/$',
        views.get_categoriza_site,
        name='get_categoriza_site'
    ),
    re_path(
        r'^revisao_manual/$',
        views.get_revisao_manual,
        name='get_revisao_manual'
    ),
    re_path(
        r'^estatisticas_axe_core/$',
        views.get_estatisticas_axe_core,
        name='get_estatisticas_axe_core'
    ),
    re_path(
        r'^estatisticas_axe_core_2/$',
        views.get_estatisticas_axe_core_cont,
        name='get_estatisticas_axe_core_cont'
    ),
    re_path(
        r'^estatisticas_3/$',
        views.get_estatisticas_cont_2,
        name='get_estatisticas_cont_2'
    ),
    re_path(
        r'^criterios_wcag/$',
        views.get_criterios_wcag,
        name='get_criterios_wcag'
    ),
    re_path(
        r'^estatisticas_wcag/$',
        views.get_estatisticas_wcag,
        name='get_estatisticas_wcag'
    ),
    re_path(
        r'^estatisticas_wcag_2/$',
        views.get_estatisticas_wcag_cont,
        name='get_estatisticas_wcag_cont'
    ),
    re_path(
        r'^testes/$',
        views.get_pandas_testes,
        name='get_pandas_testes'
    )
]